name: Install

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: install SDL2
      run: |
        sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
        sudo apt-get update -y -qq
        sudo apt-get install libsdl2-dev gcc-10
    
    - name: build and install library
      run: |
        cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Release
        sudo cmake --build build --target install
        rm -rf build
      env:
        CC: gcc-10
    
    - name: configure
      run: cmake -Htest -Bbuild -DTEST_INSTALLED_VERSION=1

    - name: build
      run: cmake --build build --config Debug -j4

    - name: test
      run: |
        ./build/b6502Tests