name: MacOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: install SDL2
      run: |
        brew install sdl2
    
    - name: configure
      run: cmake -Htest -Bbuild -DCMAKE_BUILD_TYPE=Debug

    - name: build
      run: cmake --build build -j4

    - name: test
      run: |
        ./build/b6502Tests